
# ============================================================
# CIRCUITWISE AI — IBM BOB SESSION RUNNER
# run_bob_session.py
#
# Single-command entry point for the CircuitWise AI + IBM Bob
# integration demo.
#
# USAGE:
#   python bob_context/run_bob_session.py
#
# WHAT IT DOES:
#   1. Runs export_results.py  — reads CSVs → updates JSON
#   2. Runs export_prediction.py — runs calculation + ML → updates JSON
#   3. Combines bob_prompt.md + circuitwise_results.json into
#      bob_context/bob_session_context.txt
#   4. Prints step-by-step instructions for the VS Code IBM Bob workflow
#
# REQUIRES:
#   - data/CircuitWise_AI_Anomaly_Results.csv (run ml/anomaly_detection.py)
#   - data/CircuitWise_AI_Optimization_Results.csv (run ml/optimizer.py)
#   - ml/models/power_prediction_model.pkl (run ml/train.py)
#   - bob_context/session_input.json (pre-filled with ESP32+DHT22 defaults)
#
# IBM BOB WORKFLOW (VS Code extension):
#   This script does NOT call Bob programmatically.
#   IBM Bob is used via the VS Code extension.
#   After running this script, open Bob in VS Code and paste the
#   contents of bob_context/bob_session_context.txt into the chat.
#
# ============================================================

import json
import subprocess
import sys

from pathlib import Path


# ============================================================
# PATHS
# ============================================================

SCRIPT_DIR = Path(__file__).resolve().parent
BASE_DIR = SCRIPT_DIR.parent

EXPORT_RESULTS = SCRIPT_DIR / "export_results.py"
EXPORT_PREDICTION = SCRIPT_DIR / "export_prediction.py"
BOB_PROMPT = SCRIPT_DIR / "bob_prompt.md"
RESULTS_JSON = SCRIPT_DIR / "circuitwise_results.json"
SESSION_CONTEXT_OUT = SCRIPT_DIR / "bob_session_context.txt"


# ============================================================
# HELPER: run a python script in the same interpreter
# ============================================================

def run_script(script_path):
    print(f"\n{'=' * 60}")
    print(f"  Running: {script_path.name}")
    print(f"{'=' * 60}")
    result = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=str(BASE_DIR),
        capture_output=False
    )
    if result.returncode != 0:
        print(f"\nERROR: {script_path.name} exited with code {result.returncode}.")
        print("Fix the error above before re-running run_bob_session.py.")
        raise SystemExit


# ============================================================
# BUILD BOB SESSION CONTEXT
# Combines bob_prompt.md + formatted circuitwise_results.json
# into a single plain-text file ready to paste into Bob chat.
# ============================================================

def build_context():

    print(f"\n{'=' * 60}")
    print("  Building Bob session context...")
    print(f"{'=' * 60}")

    # Load prompt
    prompt_text = BOB_PROMPT.read_text(encoding="utf-8")

    # Load and format JSON
    with open(RESULTS_JSON, "r", encoding="utf-8") as f:
        results = json.load(f)

    results_text = json.dumps(results, indent=2, ensure_ascii=False)

    # Compose context
    context = f"""\
============================================================
CIRCUITWISE AI + IBM BOB SESSION CONTEXT
============================================================
Generated by: run_bob_session.py
Timestamp: {results.get('export_timestamp', 'N/A')}
Session: {results.get('session_name', 'CircuitWise AI Session')}
============================================================

INSTRUCTIONS FOR IBM BOB (VS Code Extension):
  1. Open IBM Bob in the VS Code chat panel.
  2. Paste this entire document into the Bob chat.
  3. Bob will read the prompt and the JSON results below.
  4. Ask Bob: "Please explain the CircuitWise AI results."
  5. Use the follow-up questions in bob_prompt.md for deeper analysis.

============================================================
SECTION 1: BOB'S ROLE AND CONSTRAINTS (bob_prompt.md)
============================================================

{prompt_text}

============================================================
SECTION 2: VERIFIED CIRCUITWISE AI RESULTS (circuitwise_results.json)
============================================================

The following JSON contains ALL verified outputs from the CircuitWise AI
Python engine. Bob must reference ONLY the values in this JSON.

```json
{results_text}
```

============================================================
END OF CIRCUITWISE AI SESSION CONTEXT
============================================================
"""

    SESSION_CONTEXT_OUT.write_text(context, encoding="utf-8")
    print(f"\n  Context saved to: {SESSION_CONTEXT_OUT}")
    print(f"  Context size: {len(context):,} characters")
    return context


# ============================================================
# PRINT INSTRUCTIONS
# ============================================================

def print_instructions():

    sep = "=" * 60
    line = "-" * 45

    print(sep)
    print("  CIRCUITWISE AI + IBM BOB -- DEMO READY")
    print(sep)
    print()
    print("  Context file: bob_context/bob_session_context.txt")
    print()
    print("  HOW TO RUN THE DEMO:")
    print(f"  {line}")
    print("  1. Open VS Code in this project.")
    print("  2. Open the IBM Bob chat panel.")
    print("  3. Open bob_context/bob_session_context.txt.")
    print("  4. Select all (Ctrl+A) and copy (Ctrl+C).")
    print("  5. Paste into the Bob chat input and press Enter.")
    print('  6. Ask Bob: "Please explain the CircuitWise AI results."')
    print()
    print("  SUGGESTED FOLLOW-UP QUESTIONS:")
    print(f"  {line}")
    print('  - "What does the difference between calculated and predicted')
    print('     energy tell us about the ML model?"')
    print('  - "What does the anomaly classification mean for the hardware?"')
    print('  - "Which optimization option gives the best saving while')
    print('     keeping the ESP32 functional?"')
    print('  - "What hardware validation would you recommend?"')
    print('  - "Explain the responsible AI limitations of this analysis."')
    print()
    print("  RESPONSIBLE AI REMINDER:")
    print(f"  {line}")
    print("  All values are calculated or simulated from synthetic data.")
    print("  No hardware measurements have been taken yet.")
    print("  See RESPONSIBLE_AI.md for full details.")
    print()
    print(sep)
    print()


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 60)
    print("  CIRCUITWISE AI -- run_bob_session.py")
    print("  IBM Bob Integration -- VS Code Demo Runner")
    print("=" * 60)

    # Step 1: Export results from CSVs
    run_script(EXPORT_RESULTS)

    # Step 2: Export prediction + engineering calculation
    run_script(EXPORT_PREDICTION)

    # Step 3: Combine into session context
    build_context()

    # Step 4: Print demo instructions
    print_instructions()

    print("run_bob_session.py complete.\n")


if __name__ == "__main__":
    main()
